# -*- coding: utf-8 -*-
#
# This file is part of REANA.
# Copyright (C) 2026 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""REANA client CLI API docs generation tests."""

import importlib.util
import os

import pytest
from click.testing import CliRunner

from reana_client.cli import cli

SCRIPT_PATH = os.path.join(
    os.path.dirname(__file__), os.pardir, "scripts", "generate_cli_api.py"
)


@pytest.fixture(scope="module")
def generator():
    """Load the docs generation script as a module."""
    spec = importlib.util.spec_from_file_location("generate_cli_api", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture()
def published(generator):
    """Return a generated page surrounded by maintained prose."""
    page = generator.generate_cli_docs()
    page = page.replace(
        "# reana-client CLI API\n",
        "# reana-client CLI API\n\nFor REANA 0.9, use `REANA_ACCESS_TOKEN`.\n",
    )
    return page.replace(
        "<!-- END generated login command -->",
        "<!-- END generated login command -->\n\nMaintained login guidance.",
    )


def test_generated_page_passes_check(generator, published):
    """A page with current regions and extra prose passes."""
    assert generator.check_cli_docs(published) == []


def test_maintained_prose_edits_pass_check(generator, published):
    """Prose outside the regions can change freely."""
    edited = published.replace(
        "Maintained login guidance.", "Rewritten login guidance."
    )
    assert generator.check_cli_docs(edited) == []


def test_whitespace_changes_pass_check(generator, published):
    """Formatter whitespace and blank-line changes are ignored."""
    edited = published.replace("\n\n", "\n\n\n").replace("  ", " ")
    assert generator.check_cli_docs(edited) == []


@pytest.mark.parametrize(
    "old, new, region",
    [
        ("Show user quota.", "Show quota.", "command reference"),
        ("Authenticate against REANA server", "Sign in to REANA", "login command"),
        ("Logout from the active", "Log out of the active", "logout command"),
        ("Select a saved server", "Choose a saved server", "server command"),
    ],
)
def test_changed_descriptions_fail_check(generator, published, old, new, region):
    """A stale command description is reported for its region."""
    problems = generator.check_cli_docs(published.replace(old, new))
    assert len(problems) == 1
    assert "Region '{}".format(region) in problems[0]
    assert "differs from the CLI" in problems[0]


def test_missing_region_fails_check(generator, published):
    """A deleted region is reported rather than skipped."""
    edited = published.replace("<!-- BEGIN generated logout command -->", "")
    edited = edited.replace("<!-- END generated logout command -->", "")
    assert generator.check_cli_docs(edited) == ["Region 'logout command' is missing."]


def test_empty_region_fails_check(generator):
    """An empty region cannot pass as an empty comparison."""
    regions = generator.generate_regions()
    page = "\n".join(
        "<!-- BEGIN generated {0} -->\n{1}\n<!-- END generated {0} -->".format(
            name, "" if name == "logout command" else content
        )
        for name, content in regions.items()
    )
    assert generator.check_cli_docs(page) == ["Region 'logout command' is empty."]


def test_unknown_region_fails_check(generator, published):
    """A region the CLI no longer generates is reported."""
    edited = published + (
        "\n<!-- BEGIN generated old command -->\nx\n<!-- END generated old command -->"
    )
    assert generator.check_cli_docs(edited) == [
        "Region 'old command' is not generated by the CLI."
    ]


@pytest.mark.parametrize(
    "document, message",
    [
        (
            "<!-- BEGIN generated login command -->\n"
            "<!-- END generated login command -->\n"
            "<!-- BEGIN generated login command -->\n"
            "<!-- END generated login command -->",
            "duplicate region 'login command'",
        ),
        (
            "<!-- BEGIN generated login command -->\n"
            "<!-- BEGIN generated logout command -->",
            "region 'logout command' begins inside region 'login command'",
        ),
        (
            "<!-- END generated login command -->",
            "region 'login command' ends without beginning",
        ),
        (
            "<!-- BEGIN generated login command -->\n### login",
            "Region 'login command' is never ended",
        ),
        (
            "<!--BEGIN generated login command-->",
            "malformed region marker",
        ),
        (
            "<!-- begin generated login command -->",
            "malformed region marker",
        ),
    ],
)
def test_invalid_markers_fail_check(generator, document, message):
    """Unbalanced, duplicate and malformed markers fail clearly."""
    problems = generator.check_cli_docs(document)
    assert len(problems) == 1
    assert message in problems[0]


def test_overview_omits_reana_095_commands(generator):
    """The main overview presents the REANA 0.9 commands only."""
    overview = generator.generate_regions()["command reference"]
    for name in ("login", "logout", "server-add", "server-list"):
        assert "  {} ".format(name) not in overview
        assert "### {}\n".format(name) not in overview
    assert "Server connection management commands" not in overview
    assert "  ping " in overview


def test_overview_generation_keeps_cli_help(generator):
    """Generating the docs does not hide commands from the real CLI."""
    generator.generate_regions()
    result = CliRunner().invoke(cli, ["--help"])
    assert result.exit_code == 0
    assert "  login " in result.output
    assert "Server connection management commands" in result.output
